### ISSUE TITLE
Can't use docker image of ROS2-galactic

### ISSUE THREAD

**Issue by zhuhaier1992** [jeguzzi/robomaster_ros#8]
following instructions from here: https://github.com/jeguzzi/robomaster_ros/blob/main/docker.md
when running `docker-compose up`, it reports error:

W: GPG error: http://snapshots.ros.org/galactic/final/ubuntu focal InRelease: The following signatures were invalid: EXPKEYSIG AD19BAB3CBF125EA ROS Snapshot builder <rosbuild@ros.org>
E: The repository 'http://snapshots.ros.org/galactic/final/ubuntu focal InRelease' is not signed.

**Comment by jeguzzi** [comment]
This is a general problem when installing ROS2 distributions after their end-of-life, see https://discourse.ros.org/t/again-snapshot-repo-gpg-key-expired/34733. I don't know if it is possible to fix it. I suggest to switch to a docker file with a current version of ROS2, like `humble`. I will had a disclaimer in the docs, thanks you for pointing it out.

**Comment by jeguzzi** [comment]
I have added a disclaimer in 63ab9901c6a09e7c97f6f5688fadf6fb0cae702e.

**Comment by zhuhaier1992** [comment]
Thanks a lot :D
